spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 0927
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update # create로 두면 테이블 다 삭제하고 다시 만들어서 데이터가 이미 있는 경우에는 update로 두기
        default_batch_fetch_size: 1000